import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                //css
                "resources/scss/app.scss",
                "resources/scss/icons.scss",
                "node_modules/flatpickr/dist/flatpickr.min.css",
                "node_modules/quill/dist/quill.core.css",
                "node_modules/quill/dist/quill.snow.css",
                "node_modules/dropzone/dist/dropzone.css",
                "node_modules/quill/dist/quill.bubble.css",
                "node_modules/nouislider/dist/nouislider.min.css",
                "node_modules/swiper/swiper-bundle.min.css",
                "node_modules/@simonwep/pickr/dist/themes/classic.min.css",
                "node_modules/@simonwep/pickr/dist/themes/monolith.min.css",
                "node_modules/@simonwep/pickr/dist/themes/nano.min.css",
                "node_modules/select2/dist/css/select2.min.css",
                "node_modules/sweetalert2/dist/sweetalert2.min.css",
                "node_modules/choices.js/public/assets/styles/choices.min.css",
                "node_modules/gridjs/dist/theme/mermaid.min.css",
                "node_modules/jsvectormap/dist/jsvectormap.min.css",
                "node_modules/leaflet/dist/leaflet.css",

                //js
                "resources/js/app.js",
                "resources/js/config.js",
                "resources/js/pages/dashboard-sales.js",
                "resources/js/pages/dashboard-clinic.js",
                "resources/js/pages/dashboard-wallet.js",
                "resources/js/stock-price.js",
                "resources/js/github-data.js",
                "resources/js/irregular-data-series.js",
                "resources/js/pages/apps-calendar.js",
                "resources/js/pages/apps-email.js",
                "resources/js/pages/form-fileupload.js",
                "resources/js/pages/page-profile.js",
                "resources/js/pages/doctor-add.js",
                "resources/js/patient-chat.js",
                "resources/js/patient-chat2.js",
                "resources/js/pages/patient-details.js",
                "resources/js/pages/patient-add.js",
                "resources/js/pages/ecommerce-product-grid-list.init.js",
                "resources/js/pages/ecommerce-add-products.js",
                "resources/js/pages/sellers.js",
                "resources/js/pages/coming-soon.js",
                "resources/js/pages/extended-sweetalerts.js",
                "resources/js/pages/extended-dragula.js",
                "resources/js/pages/extended-rating.js",
                "resources/js/pages/chart-apex-area.js",
                "resources/js/pages/chart-apex-bar.js",
                "resources/js/pages/chart-apex-bubble.js",
                "resources/js/pages/chart-apex-candlestick.js",
                "resources/js/pages/chart-apex-heatmap.js",
                "resources/js/pages/chart-apex-line.js",
                "resources/js/pages/chart-apex-mixed.js",
                "resources/js/pages/chart-apex-treemap.js",
                "resources/js/pages/chart-apex-column.js",
                "resources/js/pages/chart-apex-boxplot.js",
                "resources/js/pages/chart-apex-timeline.js",
                "resources/js/pages/chart-apex-pie.js",
                "resources/js/pages/chart-apex-radar.js",
                "resources/js/pages/chart-apex-radialbar.js",
                "resources/js/pages/chart-apex-scatter.js",
                "resources/js/pages/chart-apex-polar-area.js",
                "resources/js/pages/chart-apex-sparklines.js",
                "resources/js/pages/form-inputmask.js",
                "resources/js/pages/extended-range-slider.js",
                "resources/js/pages/form-wizard.js",
                "resources/js/pages/form-fileupload.js",
                "resources/js/pages/form-quilljs.js",
                "resources/js/pages/table-gridjs.js",
                "resources/js/pages/maps-google.js",
                "resources/js/pages/maps-vector.js",
                "resources/js/pages/maps-leaflet.js",
                "resources/js/maps/canada.js",
                "resources/js/maps/iraq.js",
                "resources/js/maps/russia.js",
                "resources/js/maps/spain.js",
                "resources/js/maps/us-aea-en.js",
                "resources/js/maps/us-lcc-en.js",
                "resources/js/maps/us-mill-en.js",
                "resources/js/maps/in-mill-en.js",
                "resources/js/maps/leaflet-data.js"





            ],
            refresh: true,
        }),
    ],
    define: {
        global: 'window',
    },
});
